# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180422_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=200),
        ),
    ]
